### ISSUE TITLE
Your site doesn’t include support for the "acf/{block-name-here}" block. You can leave this block intact or remove it entirely.

### ISSUE THREAD

**Issue by ajCastiglione** [AdvancedCustomFields/acf#446] opened 2021-01-22 20:02 UTC
This issue started occurring after updating the plugin to v5.9.4. To preface this, it was working perfectly fine in v5.9.3.

I have a simple call render function that hasn't changed since updating the plugin so I'm not sure why its broken now. 

`
function my_acf_block_render_callback($block)
{
    $slug = str_replace('acf/', '', $block['name']);

    $path = get_template_directory() . "/blocks/{$slug}/{$slug}.php";
    if (file_exists($path)) {
        include($path);
    }
}
`

There's no errors in my console either so I'm at a loss.

**Comment by elliotcondon** [comment] 2021-01-23 02:06
Hi @ajCastiglione 

This error suggests that ACF was unable to register your block type during the JS initialization process run on page load. It's possible that another plugin or theme code could be the cause of this conflict - would it be possible to spin up a fresh WP site for testing (I recommend LocalByFlywheel for this).

We did implement a change in 5.9.4 which I believe will play some part in the problem, although this isn't something that will likely be reverted. The change in question is a modification to the "initialization" event. We moved away from a classic `jQuery(document).ready()` callback to the WP recommended `wp.domReady()` function.

**Comment by hamedJenabi** [comment] 2021-01-25 14:01
I had this issue also after updating to the newest version. 
Apparently updating Wordpress to 5.6 will solve the issue, but it shouldn't happen with older WP, since WP 5.6 is not required for ACF! There is definitely a bug there. 
same issue: https://support.advancedcustomfields.com/forums/topic/blocks-not-showing-in-block-editor/

**Comment by lecklin** [comment] 2021-01-28 14:33
I am also experiencing this issue on one site after updating to ACF 5.9.4. I did open a support ticket about it, so not looking for support here. Just thought I'd chime in.

I even tried to disable all plugins to rule out conflicts, but no difference.

It's very strange, as other sites with WP 5.6, ACF 5.9.4 and ACF blocks are working fine. They even have identical ACF block code, so I'm quite baffled at the moment.

**Comment by joelschlotterer** [comment] 2021-01-28 22:18
We too are experiencing this issue. WP v 5.5.3 and ACF 5.9.4 are not compatible.

**Comment by elliotcondon** [comment] 2021-01-29 04:07
Hi all 👋. Thank you for your patience whilst we tested and debugged the issue.

We have successfully identified this issue as a regression in ACF PRO 5.9.4 which caused ACF Blocks to be registered *after* the WP editor instance was initialized. This explains why new blocks could be added whilst existing blocks did not appear on page load.

Whilst we continue testing of the fix, please find an updated JS file to copy and paste into the `pro/assets/js/` folder within ACF PRO. This file contains the related patch and should solve the problem 100% - please comment bellow with your results. The quicker we can get positive feedback from you, the quicker we can release an update 🙌.

Dropbox link will be available for 7 days: https://www.dropbox.com/t/gTRoawP1TRGUgXT3

**Comment by lecklin** [comment] 2021-01-29 12:57
Unfortunately this did not work for me.
However, I think there might be different issues going on. Since some report that the combination of 5.6 and 5.9.4 works (for me not), so perhaps in the cases of pre-5.6 and ACF 5.9.4 this provided fix works.
Not to say the issues aren't related on some level.

In my case I did however notice something peculiar.
On the site I'm having issues with (WP 5.6 + ACF 5.9.4) I can see from the dev tools network tab that `acf-pro-blocks.min.js` is not loaded at all when editing a page. That naturally explains why blocks do not work.

On my "blueprint" site (also 5.6 + 5.9.4) which is running the theme I base all sites on including the one I have issues with, the file is loaded. ACF blocks work fine, including existing ones. Code related to ACF blocks is identical there as with my problematic site, although the problematic one has more blocks registered since the other is well, a blueprint. 

My question is, is there some condition when it comes to loading `acf-pro-blocks.min.js`? Or should it always be loaded, no matter what?
I'll keep trying to figure this out.
The issue popped up after updates, so no code changes from my part. That's what makes it weird.

**Comment by elliotcondon** [comment] 2021-01-29 22:59
@lecklin Thanks for the update. It does sound like you are facing a different issue, which should be easy enough to debug. 

Please open the `/pro/blocks.php` file and find the `acf_enqueue_block_assets()` function on line 440. This function is hooked into the "enqueue_block_editor_assets" action, which is run on edit screens that use the Gutenberg editor. Can you please perform some debugging to ensure this function is running as expected, and that the "acf-blocks" script is enqueued on line 480.

**Comment by lecklin** [comment] 2021-02-02 11:50
@elliotcondon nevemind, my issue was ultimately an error on my part.
I'll reply to my original support ticket with the findings.

**Comment by matthewmcvickar** [comment] 2021-02-02 23:27
The JS patch worked for me. Thank you @elliotcondon!

This may not be true for everyone’s setup, but after patching the JS file, I had to load a post in the block editor and then do a shift-refresh so it would load the new JS file. So if it doesn't work immediately, just try that.

**Comment by pinksharpii** [comment] 2021-02-03 17:09
This fix worked for us on WP 5.5.3 after a hard refresh.

**Comment by mwhiteley16** [comment] 2021-02-03 20:59
I can confirm this patch worked on multiple instances for me as well. Looks good!

**Comment by MrGlox** [comment] 2021-02-07 14:13
Hi ! Is there a way to get the JS again or updating ACF will clear the error ?

Thanks in advance !

**Comment by elliotcondon** [comment] 2021-02-07 22:41
Hi @MrGlox. An update will be out shortly containing the JS fix 🎉.

**Comment by mcyrulik** [comment] 2021-02-09 21:22
@elliotcondon When you say an update will be out shortly can you be a little more specific? This week? next week?

**Comment by elliotcondon** [comment] 2021-02-10 02:06
Hi @mcyrulik. Update is scheduled for tomorrow 👍

**Comment by elliotcondon** [comment] 2021-02-11 05:40
Hi all 👋. ACF PRO v5.9.5 is now available and includes the above mentioned fix 🎉

**Comment by jessicadesjardins** [comment] 2021-03-29 12:08
I just started experiencing this issue a couple days ago—is it possible that this bug has returned with WP 5.7?

**Comment by elliotcondon** [comment] 2021-03-29 23:27
@jessicadesjardins Sorry to hear the issue has resurfaced for you. No, we haven't been able to replicate this with 5.7. 
If possible, can you spin up a fresh WP site to test the issue isolated from any other plugins or theme code?

**Comment by andronocean** [comment] 2022-04-01 22:38
I've found a circumstance where this error still occurs. I'm trying to add one of my ACF blocks to a [block template for a post type ](https://fullsiteediting.com/lessons/creating-block-templates-for-custom-post-types/)(i.e., a "preset" group of blocks that is added automatically when creating a new post of that type). I can add the block manually and it works fine, but if the block is auto-added via the post type template, the error appears.

What's particularly strange is that the error only happens if the Gutenberg plugin is active. If it's deactivated, the template doesn't create a block at all, and instead throws an error in the browser console:

```
blocks.js?ver=28d5b8f8805a22435cbdc51927067812:2222 Uncaught (in promise) Error: Block type 'evolution/video-post-player-title' is not registered
```
Using a Core block in the template works fine.

**Comment by lgladdy** [comment] 2022-04-02 15:50
@andronocean Check the code view when you manually add the block.. what's the block called when you add it manually? I'm confused by the `evolution/` part if this is an acf block? I would expect a block to be called something like `acf/video-post-player-title`?

**Comment by andronocean** [comment] 2022-04-08 14:12
@lgladdy `evolution/` is just a namespace for blocks I'm creating inside my custom theme. Unless I've missed something I don't _think_ the `acf/` prefix is required for ACF blocks (?) I could easily change it to `acf/`, but I wanted to distinguish blocks I've defined in a functionality plugin from "layout helper" blocks I'm sourcing from the theme itself.

In any case, the prefix doesn't seem to make a difference here. If I rename it to `acf/acf-video-post-player` the same thing happens. In code view, the template block doesn't get added at all, while the manually-added one shows up normally:
```


<!-- wp:acf/acf-video-post-player {"id":"block_6250412fc6577","name":"acf/acf-video-post-player","data":{},"align":"full","mode":"preview"} /-->
```

**Comment by andronocean** [comment] 2022-04-09 19:32
Just a note that @lgladdy figured out what I had done wrong: I was trying to supply my own `evolution/` namespace, but ACF automatically puts blocks in the `acf/` namepace and sanitizes disallowed characters in the block name itself. So `evolution/video-post-player-title` became `acf/evolution-video-post-player-title`, while my template was still trying (and failing) to load it under the original name. Conclusion: let ACF take care of your block namespace 😜

**Comment by nitrokevin** [comment] 2022-10-11 22:37
I know this is an old thread but I'm getting this issue with Version 6.0.2 and PHP 8, switching back to PHP7.4 fixes the problem

**Comment by Matt633** [comment] 2022-10-24 17:37
We were having the same issue with 6.0.3 and PHP 8 -- it was working in 6, 6.0.2, and then all of a sudden we were getting the error in the editor that our "site does not support acf/[name of block]". Ultimately this came down the the JSON name -- instead of "name":  "folder/block-title", it needs to be "name: "block-title". Now it works. 

![Screen Shot 2022-10-24 at 10 32 34 AM](https://user-images.githubusercontent.com/3876577/197590053-c7abaaf9-55a6-490e-8682-c18f3f60d439.jpg)
![Screen Shot 2022-10-24 at 10 33 01 AM](https://user-images.githubusercontent.com/3876577/197590123-64c47f5f-41cc-4e72-a6a3-aae586d9a0d5.jpg)
![Screen Shot 2022-10-24 at 10 33 09 AM](https://user-images.githubusercontent.com/3876577/197590145-1f4091a9-b833-4514-959e-b8adc6ba409f.jpg)

**Comment by lgladdy** [comment] 2022-10-31 09:54
@nitrokevin @Matt633 If you're getting these errors, it's likely there is a PHP warning or something being output to your template that's meaning the result isn't parsable as JSON.

It's definitely possible `blocks` is a reserved namespace - you should definitely use something specific to your project - but I would still imagine there is a PHP warning or something explaining what the error actually is somewhere!

**Comment by Matt633** [comment] 2022-10-31 16:32
Hi Liam,

We were able to troubleshoot this, and it did seem to require us to use specific php template file names. It also required us to take off the “acf/“ from the name. That was in your documentation, and it worked until the last ACF update.

Just letting you know so that you can look into this and potentially change your documentation.

Thanks for your help!


Ours:



Yours:

Matt Davis  //  Managing Partner
Bistro Studios  //  bistro.studio

**Comment by lgladdy** [comment] 2022-11-02 10:37
Hey @Matt633,

This shouldn't matter - if you remove 'acf/' we automatically append it back; so something else must have gone on here! Feel free to drop us a support ticket if you have issues in the future though.

----

I'm going to close this issue as there isn't anything for us to do here. If you're stumbling onto this issue in the future, this error happens when either your block.json is incorrect and cannot be loaded - in our experience, this is usually something to do with the path you're trying to register the block being incorrect, or something else has gone wrong when loading your block. Your PHP error logs might give you a better idea of what's happening here, or drop us an email to support and we'll look into your specific block.

**Closed by lgladdy** 2022-11-02 10:37 UTC

**Comment by will-yellowpeach** [comment] 2022-11-14 10:30
We had the same issue when upgrading to V6.0.4. Lots of console errors with broken ACF scripts/stylesheets in the WP admin, and subsequently all our custom blocks were no longer registered. Rolled back to V6.0.3 and seems fine again

**Comment by lgladdy** [comment] 2022-11-14 13:03
@will-yellowpeach Hey Will, that's definitely not a common issue with 6.0.4's upgrade - we've not seen any other instances of it. Please contact support where they can work with you to figure out what's going wrong.
