### ISSUE TITLE
Image Field: Preview Portrait Image in Block do overflow

### ISSUE THREAD

**Issue by marcwieland95** [AdvancedCustomFields/acf#329] opened 2020-07-09 08:44 UTC
When setting a portrait image in a block, does overflow the next fields.

![CleanShot 2020-07-09 at 10 40 50](https://user-images.githubusercontent.com/6168975/87018021-ff5f1080-c1d0-11ea-8dee-b2340899d06d.png)

**Comment by elliotcondon** [comment] 2020-07-10 00:12
Hi @marcwieland95 

Thanks for the bug report. Can you please test this issue again outside of ACF Blocks?
I wonder if the problem is specific to blocks, or if it occurs in a standard metabox too.

**Comment by marcwieland95** [comment] 2020-07-21 09:32
Sorry for the late reply. Yes, same is happening outside the block.

![CleanShot 2020-07-21 at 11 31 17](https://user-images.githubusercontent.com/6168975/88037841-b6e71180-cb45-11ea-8394-4179887c9c1c.png)

**Comment by elliotcondon** [comment] 2020-07-22 00:42
Thanks @marcwieland95. This is good news in that the bug is not specific to Block markup.

All that is left for me to do is replicate the bug and figure out what is failing. Is there any chance you have a staging site online where I can quickly login and see the issue? I'll try setting up the problem locally, but have a feeling this issue may be also caused by missing cropped image sizes.

**Comment by matthewmcvickar** [comment] 2020-07-22 01:23
I *just* had this issue the other day and had it on my todo list to make a bug report! 😃

**Comment by marcwieland95** [comment] 2020-07-23 07:38
No, I do not have a staging environment yet.

I checked it with cropped images. And somehow you're in the right direction.
When I change to "original size" in the field then it starts to work. In all other sizes I choose, it doesn't. But the image size is available in the upload folder. As a fallback, the original images gets loaded.

![CleanShot 2020-07-23 at 09 36 23@2x](https://user-images.githubusercontent.com/6168975/88262335-47e5f600-ccc8-11ea-8f95-cf27cd0bd414.png)

**Comment by elliotcondon** [comment] 2020-07-23 23:34
@marcwieland95 Intersting... So the field settings show the preview_size is "thumbnail", but the image URL loaded is the full size. It sounds like WP is unable to load the thumbnail URL for that image, and is defaulting to the full size instead.

**Comment by matthewmcvickar** [comment] 2020-07-24 16:59
@elliotcondon Could this output just rely on `wp_get_attachment_image()` and then resize with CSS, rather than relying on inline CSS in the `.image-wrap` container?

**Comment by elliotcondon** [comment] 2020-07-25 22:44
Hi @matthewmcvickar 

I have plans to implement this in the future. The reason why we use a custom `<img />` tag is so that our JS can update the element using the WP media modal attachment response data.

**Comment by matthewmcvickar** [comment] 2020-07-25 23:53
@elliotcondon Ah, I see. That makes sense.

In the meantime, this CSS seems to solve the issue:

```css
.acf-field .image-wrap img {
  max-height: 100%;
}
```

([Here’s a nice snippet for adding a custom stylesheet to the admin.](https://developer.wordpress.org/reference/hooks/admin_enqueue_scripts/#comment-69))

**Comment by elliotcondon** [comment] 2020-07-27 00:18
Good news 🎉. I've applied a fix for this issue, and will include in the upcoming 5.9.0 release.

**Closed by elliotcondon** 2020-07-27 00:18 UTC

**Comment by marcwieland95** [comment] 2020-07-28 08:27
Thanks. That was fast. I love tickets like that.
