### ISSUE TITLE
Current Gutenberg Plugin Version 11.8.3 breaks ability to save/access HTML Anchor field values

### ISSUE THREAD

**Issue by albanyacademy** [AdvancedCustomFields/acf#567] opened 2021-11-09 19:02 UTC
Just in case anyone else comes here looking for an answer, it's not ACF's fault.

Saved values are still accessible from the theme code, its just the Block > Advanced > HTML Anchor field does effectively nothing.

WP 5.8.1
ACF Pro 5.10.2
Gutenberg Plugin 11.8.3 (seems like it stops working at 11.8.0)

Steps:
1. Have both plugins installed w/ appropriate versions
2. Declare custom ACF block with supports anchor true
3. Navigate to a page and add a block
4. Attempting to save a value into the anchor field and then refreshing a page shows a blank field - changes are not reflected in the front end either.
5. Manually entering the anchor field value in the DB reflects the change in the frontend but does not show anything in the editor view.
6. Upon saving, any preexisting saved anchor value in the DB is missing.

I'd log this on the gutenberg repo but their bug report asks if I've verified whether or not I've disabled all other plugins than gutenberg.

**Comment by nick6352683** [comment] 2021-11-09 21:58
WP 5.8.1, ACF PRO 5.10.2, Gutenberg Plugin 11.8.3 - so same as above...

Refresh the browser cache both on front and back ends to make sure...

I have no issues as mentioned above - the anchors work fine as always... make sure your theme or another plugin is not causing some sort of a conflict.

As a quick fix for your case, if this issue comes up only with ACF Blocks, put your ACF Block inside a Group Block, and enter the anchor values in the Group Block - it's an extra step, but that would do the trick if the issue does not include the core blocks.

**Comment by nick6352683** [comment] 2021-11-10 19:08
Correction from above - my WP version was 5.8.2, and not 5.8.1, may be that is the cause of the issue?

**Comment by wolfgegenlicht** [comment] 2022-01-13 20:57
yep, got the same problem and behaviour! Anchor just won't save.

**Comment by nick6352683** [comment] 2022-01-21 07:29
Ok, now I'm experiencing this too...

WordPress WP 5.9 RC23
ACF Pro 5.11.4
No Gutenberg plugin.

One easy solution for me was to put my ACF block in a core container block, such as the Group, Cover or Columns block, and assign the anchor value there...

**Comment by lgladdy** [comment] 2022-01-24 18:32
Thanks for the report. We're aiming to have an ACF beta release tomorrow alongside WordPress 5.9's release. We'll get this issue tested against that build and see if we need to make further changes in subsequent builds to fix!

**Comment by lgladdy** [comment] 2022-01-25 08:22
Just to confirm we've been able to reproduce this bug. We're unlikely to get a fix in time for ACF 5.12-beta1 later today, but we'll get it in as soon as possible after!

**Comment by lgladdy** [comment] 2022-02-10 08:17
Hey everyone 👋 

This issue is fixed in ACF PRO 5.12-beta2 which you can download from your account.

The final release should be out in the next couple of weeks if you'd prefer to wait!

**Comment by cbirdsong** [comment] 2022-02-16 15:38
Do existing anchors work?

**Comment by lgladdy** [comment] 2022-02-16 15:41
@cbirdsong Should do! Are you seeing any issues? This issue should have only affected new or modified blocks.

**Comment by cbirdsong** [comment] 2022-02-16 17:40
No, just double checking!

**Comment by hannahmwool** [comment] 2022-02-18 18:06
@cbirdsong They work but if you update the page they've been emptying out so watch for that.

**Comment by MichaelRise** [comment] 2022-02-23 10:06
Hey,
I have this same problem. When we use `'supports' =>  [ 'anchor' => true ]` anchor field is visible, but not saved.
WP 5.9
ACF 5.11.4
I found similar topic https://github.com/elliotcondon/acf/issues/768 - Maybe WP helper function blocks saving "anchor" attribute.

**Comment by lgladdy** [comment] 2022-02-23 10:10
@MichaelRise As above, this is fixed in 5.12-RC1 which you can download from your account and will be in our final 5.12 release :)

**Closed** 2022-05-12 15:01 UTC
