### ISSUE TITLE
Loading ACF fields: Performance issues since version 5.8.5

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#240] opened 2019-10-21 10:22 UTC
Hey Elliot,

I've question about loading ACF fields. I'm using more than 100 field groups and have trouble with the page loading speed and ACF. There a 3 methods to load the field groups:

**PHP exported fields:**

 include( plugin_dir_path( __DIR__ ) . acf-field-groups.php' );

<img width="207" alt="Bildschirmfoto 2019-10-21 um 12 10 59" src="https://user-images.githubusercontent.com/31563167/67196861-e5d82780-f3fb-11e9-9a1e-2c7337b6a590.png">

**Local JSON:**

add_filter('acf/settings/load_json', ...

<img width="206" alt="Bildschirmfoto 2019-10-21 um 12 13 00" src="https://user-images.githubusercontent.com/31563167/67196996-2f287700-f3fc-11e9-96d2-976f5d68de1e.png">

**Fields from database:**

<img width="206" alt="Bildschirmfoto 2019-10-21 um 12 14 32" src="https://user-images.githubusercontent.com/31563167/67197109-67c85080-f3fc-11e9-875c-4c5cd20be556.png">

But I can not understand why the "PHP exported fields" and "Local JSON" methods are slower than calling the fields directly from the database? Direct calling of the fields from the database should be slower, right?

Can you help me to understand this issue?

**Comment by CreativeDive** [comment] 2019-10-21 12:24
@elliotcondon Now I've more details. The reason of this issue is the embedded ACF plugin folder. I have included ACF directly inside my plugin by:

```
if( ! class_exists( 'acf' ) ) { 
	
	// Path to the ACF plugin of the [ THEME HELPER PLUGIN ] 
	nclude_once( plugin_dir_path( __FILE__ ) . 'inc/acf/acf.php' );
	
}
```

If I manually activate the ACF plugin by the backend, the loading time is faster. Because the installed plugin will used instead, managed by `if( ! class_exists( 'acf' ) )`. But after deactivating ACF again, the loading time is increased.

So we can see, including ACF like: https://www.advancedcustomfields.com/resources/including-acf-within-a-plugin-or-theme/

Slows down the page load time. But how we can solve this special case? Should ACF always be loaded before loading all the other plugins?

How we can handle this special case, if ACF is included in a plugin? Is there a possible hook, to load ACF in the same way like installing the plugin manually?

**Comment by CreativeDive** [comment] 2019-10-21 18:03
@elliotcondon I dived deeper into this issue. There was a little misunderstanding.

Unfortunately I still had **ACF 5.8** plugin installed and included **ACF 5.8.5** as a package in my plugin. For this reason, there are also these essential performance differences. I've noticed a significant speed loss now, if we compare the version ACF 5.8 with ACF 5.8.5.

Test ACF 5.8:

<img width="198" alt="Bildschirmfoto 2019-10-21 um 19 50 50" src="https://user-images.githubusercontent.com/31563167/67229696-1f308780-f43c-11e9-93f6-bf0349f417aa.png">

Test ACF 5.8.1:

<img width="197" alt="Bildschirmfoto 2019-10-21 um 19 52 42" src="https://user-images.githubusercontent.com/31563167/67229818-5ef76f00-f43c-11e9-932a-c6153996db5e.png">

Test ACF 5.8.2:

<img width="201" alt="Bildschirmfoto 2019-10-21 um 19 54 11" src="https://user-images.githubusercontent.com/31563167/67229911-9239fe00-f43c-11e9-90dd-4b0d3c5fc6c6.png">

Test ACF 5.8.3:

<img width="196" alt="Bildschirmfoto 2019-10-21 um 19 55 45" src="https://user-images.githubusercontent.com/31563167/67230032-cc0b0480-f43c-11e9-8146-d6c8ac1e5526.png">

Test ACF 5.8.4:

<img width="202" alt="Bildschirmfoto 2019-10-21 um 19 57 05" src="https://user-images.githubusercontent.com/31563167/67230116-fb217600-f43c-11e9-9a55-af41910ebf34.png">

Test ACF 5.8.5:

<img width="195" alt="Bildschirmfoto 2019-10-21 um 19 59 33" src="https://user-images.githubusercontent.com/31563167/67230288-5489a500-f43d-11e9-9047-be26cae10e05.png">

The current load time with ACF has significant increased since version 5.8.5. Please fix this issue. For all tests, the fields were loaded with local JSON.

**Comment by elliotcondon** [comment] 2019-10-21 21:23
Hi @CreativeDive 

Thanks for the bug report,
Elliot here - ACF dev​​​.

Great work testing out the issue across different versions and reporting back the load times.
I'm shocked to see such a performance hit in out latest version, and I wonder if this the result of a recent fix we applied.

When you next have the chance, can you please edit the file `includes/local-fields.php` and comment out line 371 like so:
```
// $field['menu_order'] = acf_count_local_fields( $field['parent'] );
```

I'm interested to know if this solves the performance issue. If so, I'll need to perform some testing of my own and head back to the "drawing board" on how to fix this without causing other issues for local fields.

**Comment by CreativeDive** [comment] 2019-10-21 21:48
@elliotcondon thank you for replay.

I've commented out this line and wow, yes this is the performance killer in ACF 5.8.5. After commenting out this line, the load time is the same as in ACF 5.8.4 and earlier.

**Comment by elliotcondon** [comment] 2019-10-21 21:50
@CreativeDive Thanks mate. I'm glad to hear we identified the issue. I'll aim to have this fixed within the next few versions :)

**Comment by nick6352683** [comment] 2019-10-21 21:53
In the meantime..., can we just comment out that line (371), without experiencing some weird side effects, or there is more to this... 

Thanks to both of you on this btw...,

**Comment by elliotcondon** [comment] 2019-10-21 21:55
@nick6352683 Commenting out this line should introduce only a single effect:

When syncing fields (from the local acf-json folder), fields will be saved with a "menu_order" of 0 which can lead to "field order issues".

If you are not planning to use the "sync" feature, there should be nothing to worry about.

**Comment by nick6352683** [comment] 2019-10-21 21:57
Thanks Elliot,

Everything is clear now...

**Comment by CreativeDive** [comment] 2019-11-13 07:27
Hey @elliotcondon, 
I wonder when you solve this performance issue? Is there a reason why it has not been solved yet?

**Comment by elliotcondon** [comment] 2019-11-14 00:18
Hi @CreativeDive - Thanks for the prompt. This issue has been at the top of my internal to-do, but has unfortunately been pushed back due to some other pressing matters including our Pricing Change Announcement and the WordPress 5.3 release.

I'm hoping to spin up a site shortly, and replicate this issue by generating a large number of field groups.

Keep using the previously mentioned fix for now. I'll hopefully have something to share soon.

**Comment by elliotcondon** [comment] 2019-11-14 22:19
Update: I'm currently working on this issue and hope to find a solution shortly.

In testing, I have been able to successfully replicate the slow load time caused by the `acf_count_local_fields()` function. I have also identified other performance bottlenecks in the "Local Fields" implementation.

Currently investigating a few ideas.

**Comment by CreativeDive** [comment] 2019-11-15 07:30
@elliotcondon Performance optimization sounds really really good :-)

**Comment by coleplx** [comment] 2020-11-06 17:30
Hello guys, any update on this issue?

I have a customer with loading speed hitting ~15s when this line is uncommented:
root@xxxx# time wp plugin list --allow-root
real	0m15.291s

After commenting this line, loading time decreases to ~2s:
real	0m1.362s

**Comment by elliotcondon** [comment] 2020-11-07 22:06
Thanks @coleplx. No update just yet, but we will hope to have this rectified soon.

**Comment by dermonotone** [comment] 2021-02-08 12:37
Hi there, is there any update about this issue?

we have serious speed problems because of the bug.
Thanks in advance

**Comment by davefx** [comment] 2021-02-17 20:21
@elliotcondon Would it cause any problem if we disable this line only for non-backend and ajax calls?

```php
if (is_admin() && ! defined('DOING_AJAX')) {
    $field['menu_order'] = acf_count_local_fields( $field['parent'] );
}
```
Thanks!

**Comment by elliotcondon** [comment] 2021-02-17 20:56
Hi @davefx. I've searched over the codebase and believe this should be fine. Perhaps a simpler alternative is to comment out the "menu_order" line completely. This field property is not crucial to the plugin's functionality.

I would like to take this moment to once again apologize for the performance issue regression caused in version 5.8.5. The refactor changes made in this version that lead to the performance bottleneck are a longstanding regret of mine, and I am positive it is something that will get fixed. Our attention has lately been held by WordPress' faster pace releases around the Gutenberg editor, but I intend to return our focus back to PHP core issues in the near future.

**Comment by jamieschmid** [comment] 2021-04-14 03:54
Hello! Not trying to put more stress on you over this, but I too noticed a significant performance hit with the update. I tried to comment out the menu_order line, but the code has changed since posting this and this no longer exists. Can you give an update on 1. if this fix still works; 2. what the new line to comment out is; and 3. a (tiny) update on where this is in your priorities list? We are using ACF fields heavily in our ACF blocks and I'm struggling to improve performance any further.

We are also using the PRELOAD BLOCKS constant which did help somewhat. 

Thank you!

**Closed** 2022-10-12 15:16 UTC
