### ISSUE TITLE
ACF currently includes a lot of PHP 8 deprecated messages

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#433] opened 2021-01-07 11:57 UTC
Hey @elliotcondon;

I'm switched to PHP 8 and get a lot of PHP deprecated messages. 

At this time I get all this deprecated messages only for one type like: [https://php.watch/versions/8.0/deprecate-required-param-after-optional](url)

I think a lot of functions are affected.

<img width="1285" alt="Bildschirmfoto 2021-01-07 um 12 56 28" src="https://user-images.githubusercontent.com/31563167/103890108-c8b67400-50e7-11eb-9451-593225934de1.png">

How do you think? Do you can solve it with the upcoming update?

**Comment by elliotcondon** [comment] 2021-01-07 22:57
Thanks @CreativeDive 

I'll close this ticket as a duplicate of https://github.com/AdvancedCustomFields/acf/issues/423. Rest assured these warnings will be fixed shortly.

**Closed by elliotcondon** 2021-01-07 22:57 UTC
